import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { writeProjectFiles, runInstall } from "@/lib/workspace";
import { type GeneratedFile, inferLanguage } from "@/lib/forge-config";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// POST /api/projects/[id]/deepseek-save
// Saves files generated by DeepSeek (via the DeepseekWebview component) to
// the project's database record and writes them to disk.
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const body = await request.json();
    const { files, prd }: { files: GeneratedFile[]; prd: string } = body;

    if (!files || !Array.isArray(files) || files.length === 0) {
      return NextResponse.json(
        { success: false, error: "Aucun fichier fourni" },
        { status: 400 }
      );
    }

    const project = await db.project.findUnique({ where: { id } });
    if (!project) {
      return NextResponse.json(
        { success: false, error: "Projet introuvable" },
        { status: 404 }
      );
    }

    // Normalize files
    const normalizedFiles: GeneratedFile[] = files.map((f) => ({
      path: String(f.path),
      content: String(f.content ?? ""),
      language: f.language || inferLanguage(String(f.path)),
    }));

    // Update project in DB
    await db.project.update({
      where: { id },
      data: {
        filesJson: JSON.stringify(normalizedFiles),
        fileCount: normalizedFiles.length,
        prd: prd || project.prd,
        status: "ready",
        buildStatus: "pending",
        installStatus: "pending",
        updatedAt: new Date(),
      },
    });

    // Write files to disk
    try {
      await writeProjectFiles(id, normalizedFiles);
      // Trigger npm install in background
      runInstall(id);
    } catch (diskErr) {
      console.error("[deepseek-save] writeProjectFiles failed:", diskErr);
      // Non-fatal: files are in DB
    }

    return NextResponse.json({
      success: true,
      fileCount: normalizedFiles.length,
      message: `${normalizedFiles.length} fichiers sauvegardés`,
    });
  } catch (error) {
    console.error("[/api/projects/[id]/deepseek-save]", error);
    return NextResponse.json(
      { success: false, error: "Impossible de sauvegarder" },
      { status: 500 }
    );
  }
}
